### ISSUE TITLE
Is there a way to log caught exceptions to Rollbar from class components?

### ISSUE THREAD

**Issue by leosoaivan** [rollbar/rollbar-react#17]
Is there a way to log caught exceptions to Rollbar from class components using `@rollbar/react`?

At present, it appears that `Provider` and `ErrorBoundary` only log uncaught exceptions. Logging caught exceptions in functional components seems to be possible using the `useRollbar` hook to access the Rollbar instance created by `Provider`.

Is there a way something similar can be achieve for children class components, or would I also have to import `rollbar` and instantiate it myself in class components? Or perhaps create a HOC that passes in the `rollbar` instance?

**Comment by calvinf** [comment]
With the prevalence of functional components in the React ecosystem, I'd suggest migrating to that pattern and using the hook where possible.

If you really need to send it to a class component, the approaches you mentioned sound reasonable... wrap in another component that gets the `rollbar` instance from the hook and pass it into the relevant child component.

**Comment by waltjones** [comment]
When using the Provider component, the Rollbar instance is stored in a React Context. There are standard ways to get the value from a Context in a class component, but this SDK is missing the needed exports. I have opened a PR to provide these. (https://github.com/rollbar/rollbar-react/pull/38)

There are several ways to make the Rollbar instance available to class components. Each may be best in different situations.

### 1. Get the instance from the Context
This will only work once the above PR is published. This technique should be preferred for projects that are migrating to function components, or have a mix of class and function components.
```
import React from 'react';
import { Context, getRollbarFromContext } from '@rollbar/react';

export default class ClassComponent extends React.Component {
  // This must always be named `contextType`. It's a special React property
  static contextType = Context; .

  componentDidMount() {
    // This will be set when the component is mounted.
    this.rollbar = getRollbarFromContext(this.context);

    this.rollbar.info('message from class component');
  }

  render() {
    return <div>Class component</div>
  }
}
```
This pattern only works when your class consumes a single context. If your class consumes multiple Contexts, you have to wrap the class component instead:
```
    <OtherContext.Consumer>
      {other => (
        <RollbarContext.Consumer>
          {rollbarContext => (
            <ClassComponent other={other} rollbarContext={rollbarContext} />
          )}
        </RollbarContext.Consumer>
      )}
    </OtherContext.Consumer>
```
That's a bit awkward, but that's why people are migrating to function components and hooks. Constructs like this aren't needed when using hooks.

Note that in the class component, you still need to get the instance out of the context:
`this.rollbar = getRollbarFromContext(this.props.rollbarContext);`

### 2. Store the instance in whatever state management you use.
If your project is primarily class components, and you aren't planning to migrate from that, you're probably using some state management solution. e.g. redux or mobx. In this case, the provider isn't that useful and you can just instantiate the rollbar instance and store it in your global state.
```
// At the top of <App>
import Rollbar from 'rollbar';

// Put this in your global state
const rollbar = new Rollbar(config);
```

### 3. Attach the instance to the window object
If your project is too small to have state management, and you don't plan to migrate to function components, you can attach it to the window object. That's what Rollbar.js does by default, and it will work fine to do it here as well.
```
window.rollbar = new Rollbar(config);

// You can now use it from anywhere in your app.
rollbar.info('It works!');
```
