### ISSUE TITLE
React Hook "useRollbarPerson" cannot be called inside a callback

### ISSUE THREAD

**Issue by ErikCoup** [rollbar/rollbar-react#21]
Hi, I am trying to utilize the `useRollbarPerson` following the example provided in the documentation. I run into the following build error (the project uses Next.js with TypeScript), though:

```
Error: React Hook "useRollbarPerson" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function.  react-hooks/rules-of-hooks
```

I assume this is a combination of the function name starting with `use` and it not being used in the function component itself. I am trying to use the function, as the example in the documentation here does, within a `useEffect` hook.

Is there maybe a proposed way around this issue? Or should this function possibly be renamed (e.g., `setRollbarPerson`)?

**Comment by calvinf** [comment]
The error message is a general error React shows when you're mis-using hooks.

See: https://reactjs.org/docs/hooks-rules.html

**Comment by ijsnow** [comment]
As calvin mentioned, the issue is actually with the usage of a react hook. In order to use any react hook, it has to be at the top level scope of your function component and before any control flow statements such as an if statement. This is an effect of how react hooks work internally. 

You'll have to follow those requirements which will be fine for the case where you just want it ran when useEffect would run since the hook does this internally (it will only get called when it needs to). Alternatively you can do what the hook does under the hood in your function component which would look like this for the user hook:

```javascript
  const rollbar = useRollbar();

  rollbar.configure({
    payload: { person }
  });
```

**Comment by cyrusradfar** [comment]
@shem8 thanks for the suggestion, will discuss w the team! Appreciate the proactive nudge 😃

**Comment by zbyte64** [comment]
Not having hooks that return setter callbacks leads to awkward usage.

**Comment by ijsnow** [comment]
@zbyte64 I hear ya! I think in the end the current implementation results in less code for the user since the library handles ensuring the object actually changes/memoizing calls internally but I can add another hook (e.g. `useRollbarPersonSetter`) that returns a setter to support both modalities discussed in this issue without requiring the knowledge of the [rollbar instances's api mentioned here.](https://github.com/rollbar/rollbar-react/issues/21#issuecomment-1041087755)
